// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/yano.proto

package hu.unideb.inf.batfai.yanonymous8;

public final class YanoProto {
  private YanoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 meId = 1;
    /**
     * <code>required int32 meId = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    boolean hasMeId();
    /**
     * <code>required int32 meId = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    int getMeId();

    // optional int32 id = 2;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    int getId();

    // required .Person.Chosen chosen = 3;
    /**
     * <code>required .Person.Chosen chosen = 3;</code>
     */
    boolean hasChosen();
    /**
     * <code>required .Person.Chosen chosen = 3;</code>
     */
    hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen getChosen();

    // optional .Person.Relations relations = 4;
    /**
     * <code>optional .Person.Relations relations = 4;</code>
     */
    boolean hasRelations();
    /**
     * <code>optional .Person.Relations relations = 4;</code>
     */
    hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations getRelations();
    /**
     * <code>optional .Person.Relations relations = 4;</code>
     */
    hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.RelationsOrBuilder getRelationsOrBuilder();
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              meId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen value = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                chosen_ = value;
              }
              break;
            }
            case 34: {
              hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = relations_.toBuilder();
              }
              relations_ = input.readMessage(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(relations_);
                relations_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.class, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Person.Chosen}
     *
     * <pre>
     * Kit/mit választott
     * </pre>
     */
    public enum Chosen
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Android = 1;</code>
       */
      Android(0, 1),
      /**
       * <code>iOS = 2;</code>
       */
      iOS(1, 2),
      /**
       * <code>Windows = 3;</code>
       */
      Windows(2, 3),
      /**
       * <code>Others = 4;</code>
       */
      Others(3, 4),
      ;

      /**
       * <code>Android = 1;</code>
       */
      public static final int Android_VALUE = 1;
      /**
       * <code>iOS = 2;</code>
       */
      public static final int iOS_VALUE = 2;
      /**
       * <code>Windows = 3;</code>
       */
      public static final int Windows_VALUE = 3;
      /**
       * <code>Others = 4;</code>
       */
      public static final int Others_VALUE = 4;


      public final int getNumber() { return value; }

      public static Chosen valueOf(int value) {
        switch (value) {
          case 1: return Android;
          case 2: return iOS;
          case 3: return Windows;
          case 4: return Others;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Chosen>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Chosen>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Chosen>() {
              public Chosen findValueByNumber(int number) {
                return Chosen.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final Chosen[] VALUES = values();

      public static Chosen valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Chosen(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.Chosen)
    }

    public interface RelationsOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // repeated .Person Person = 1;
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> 
          getPersonList();
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      hu.unideb.inf.batfai.yanonymous8.YanoProto.Person getPerson(int index);
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      int getPersonCount();
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      java.util.List<? extends hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> 
          getPersonOrBuilderList();
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder getPersonOrBuilder(
          int index);

      // required .Person.Relations.Relation relation = 2;
      /**
       * <code>required .Person.Relations.Relation relation = 2;</code>
       */
      boolean hasRelation();
      /**
       * <code>required .Person.Relations.Relation relation = 2;</code>
       */
      hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation getRelation();
    }
    /**
     * Protobuf type {@code Person.Relations}
     */
    public static final class Relations extends
        com.google.protobuf.GeneratedMessage
        implements RelationsOrBuilder {
      // Use Relations.newBuilder() to construct.
      private Relations(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Relations(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Relations defaultInstance;
      public static Relations getDefaultInstance() {
        return defaultInstance;
      }

      public Relations getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Relations(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  person_ = new java.util.ArrayList<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person>();
                  mutable_bitField0_ |= 0x00000001;
                }
                person_.add(input.readMessage(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.PARSER, extensionRegistry));
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation value = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  relation_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_Relations_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_Relations_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.class, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Builder.class);
      }

      public static com.google.protobuf.Parser<Relations> PARSER =
          new com.google.protobuf.AbstractParser<Relations>() {
        public Relations parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Relations(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Relations> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code Person.Relations.Relation}
       */
      public enum Relation
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>Relational = 1;</code>
         *
         * <pre>
         * rokoni
         * </pre>
         */
        Relational(0, 1),
        /**
         * <code>Friend = 2;</code>
         *
         * <pre>
         * barát
         * </pre>
         */
        Friend(1, 2),
        /**
         * <code>Girlfriend = 3;</code>
         *
         * <pre>
         * csajom
         * </pre>
         */
        Girlfriend(2, 3),
        /**
         * <code>Boyfriend = 4;</code>
         *
         * <pre>
         * pasim
         * </pre>
         */
        Boyfriend(3, 4),
        /**
         * <code>Father = 5;</code>
         *
         * <pre>
         * apa
         * </pre>
         */
        Father(4, 5),
        /**
         * <code>Mother = 6;</code>
         *
         * <pre>
         * anya
         * </pre>
         */
        Mother(5, 6),
        /**
         * <code>Neighbor = 7;</code>
         *
         * <pre>
         * szomszéd
         * </pre>
         */
        Neighbor(6, 7),
        ;

        /**
         * <code>Relational = 1;</code>
         *
         * <pre>
         * rokoni
         * </pre>
         */
        public static final int Relational_VALUE = 1;
        /**
         * <code>Friend = 2;</code>
         *
         * <pre>
         * barát
         * </pre>
         */
        public static final int Friend_VALUE = 2;
        /**
         * <code>Girlfriend = 3;</code>
         *
         * <pre>
         * csajom
         * </pre>
         */
        public static final int Girlfriend_VALUE = 3;
        /**
         * <code>Boyfriend = 4;</code>
         *
         * <pre>
         * pasim
         * </pre>
         */
        public static final int Boyfriend_VALUE = 4;
        /**
         * <code>Father = 5;</code>
         *
         * <pre>
         * apa
         * </pre>
         */
        public static final int Father_VALUE = 5;
        /**
         * <code>Mother = 6;</code>
         *
         * <pre>
         * anya
         * </pre>
         */
        public static final int Mother_VALUE = 6;
        /**
         * <code>Neighbor = 7;</code>
         *
         * <pre>
         * szomszéd
         * </pre>
         */
        public static final int Neighbor_VALUE = 7;


        public final int getNumber() { return value; }

        public static Relation valueOf(int value) {
          switch (value) {
            case 1: return Relational;
            case 2: return Friend;
            case 3: return Girlfriend;
            case 4: return Boyfriend;
            case 5: return Father;
            case 6: return Mother;
            case 7: return Neighbor;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Relation>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<Relation>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Relation>() {
                public Relation findValueByNumber(int number) {
                  return Relation.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.getDescriptor().getEnumTypes().get(0);
        }

        private static final Relation[] VALUES = values();

        public static Relation valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private Relation(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:Person.Relations.Relation)
      }

      private int bitField0_;
      // repeated .Person Person = 1;
      public static final int PERSON_FIELD_NUMBER = 1;
      private java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> person_;
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> getPersonList() {
        return person_;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public java.util.List<? extends hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> 
          getPersonOrBuilderList() {
        return person_;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public int getPersonCount() {
        return person_.size();
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person getPerson(int index) {
        return person_.get(index);
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder getPersonOrBuilder(
          int index) {
        return person_.get(index);
      }

      // required .Person.Relations.Relation relation = 2;
      public static final int RELATION_FIELD_NUMBER = 2;
      private hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation relation_;
      /**
       * <code>required .Person.Relations.Relation relation = 2;</code>
       */
      public boolean hasRelation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Person.Relations.Relation relation = 2;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation getRelation() {
        return relation_;
      }

      private void initFields() {
        person_ = java.util.Collections.emptyList();
        relation_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation.Relational;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasRelation()) {
          memoizedIsInitialized = 0;
          return false;
        }
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < person_.size(); i++) {
          output.writeMessage(1, person_.get(i));
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(2, relation_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < person_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, person_.get(i));
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, relation_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Person.Relations}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.RelationsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_Relations_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_Relations_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.class, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Builder.class);
        }

        // Construct using hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getPersonFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (personBuilder_ == null) {
            person_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            personBuilder_.clear();
          }
          relation_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation.Relational;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_Relations_descriptor;
        }

        public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations getDefaultInstanceForType() {
          return hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.getDefaultInstance();
        }

        public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations build() {
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations buildPartial() {
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations result = new hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (personBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              person_ = java.util.Collections.unmodifiableList(person_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.person_ = person_;
          } else {
            result.person_ = personBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000001;
          }
          result.relation_ = relation_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations) {
            return mergeFrom((hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations other) {
          if (other == hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.getDefaultInstance()) return this;
          if (personBuilder_ == null) {
            if (!other.person_.isEmpty()) {
              if (person_.isEmpty()) {
                person_ = other.person_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensurePersonIsMutable();
                person_.addAll(other.person_);
              }
              onChanged();
            }
          } else {
            if (!other.person_.isEmpty()) {
              if (personBuilder_.isEmpty()) {
                personBuilder_.dispose();
                personBuilder_ = null;
                person_ = other.person_;
                bitField0_ = (bitField0_ & ~0x00000001);
                personBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getPersonFieldBuilder() : null;
              } else {
                personBuilder_.addAllMessages(other.person_);
              }
            }
          }
          if (other.hasRelation()) {
            setRelation(other.getRelation());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRelation()) {
            
            return false;
          }
          for (int i = 0; i < getPersonCount(); i++) {
            if (!getPerson(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // repeated .Person Person = 1;
        private java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> person_ =
          java.util.Collections.emptyList();
        private void ensurePersonIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = new java.util.ArrayList<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person>(person_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            hu.unideb.inf.batfai.yanonymous8.YanoProto.Person, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> personBuilder_;

        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> getPersonList() {
          if (personBuilder_ == null) {
            return java.util.Collections.unmodifiableList(person_);
          } else {
            return personBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public int getPersonCount() {
          if (personBuilder_ == null) {
            return person_.size();
          } else {
            return personBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person getPerson(int index) {
          if (personBuilder_ == null) {
            return person_.get(index);
          } else {
            return personBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder setPerson(
            int index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person value) {
          if (personBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePersonIsMutable();
            person_.set(index, value);
            onChanged();
          } else {
            personBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder setPerson(
            int index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder builderForValue) {
          if (personBuilder_ == null) {
            ensurePersonIsMutable();
            person_.set(index, builderForValue.build());
            onChanged();
          } else {
            personBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder addPerson(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person value) {
          if (personBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePersonIsMutable();
            person_.add(value);
            onChanged();
          } else {
            personBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder addPerson(
            int index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person value) {
          if (personBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePersonIsMutable();
            person_.add(index, value);
            onChanged();
          } else {
            personBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder addPerson(
            hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder builderForValue) {
          if (personBuilder_ == null) {
            ensurePersonIsMutable();
            person_.add(builderForValue.build());
            onChanged();
          } else {
            personBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder addPerson(
            int index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder builderForValue) {
          if (personBuilder_ == null) {
            ensurePersonIsMutable();
            person_.add(index, builderForValue.build());
            onChanged();
          } else {
            personBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder addAllPerson(
            java.lang.Iterable<? extends hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> values) {
          if (personBuilder_ == null) {
            ensurePersonIsMutable();
            super.addAll(values, person_);
            onChanged();
          } else {
            personBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder clearPerson() {
          if (personBuilder_ == null) {
            person_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            personBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public Builder removePerson(int index) {
          if (personBuilder_ == null) {
            ensurePersonIsMutable();
            person_.remove(index);
            onChanged();
          } else {
            personBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder getPersonBuilder(
            int index) {
          return getPersonFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder getPersonOrBuilder(
            int index) {
          if (personBuilder_ == null) {
            return person_.get(index);  } else {
            return personBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public java.util.List<? extends hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> 
             getPersonOrBuilderList() {
          if (personBuilder_ != null) {
            return personBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(person_);
          }
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder addPersonBuilder() {
          return getPersonFieldBuilder().addBuilder(
              hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.getDefaultInstance());
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder addPersonBuilder(
            int index) {
          return getPersonFieldBuilder().addBuilder(
              index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.getDefaultInstance());
        }
        /**
         * <code>repeated .Person Person = 1;</code>
         */
        public java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder> 
             getPersonBuilderList() {
          return getPersonFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            hu.unideb.inf.batfai.yanonymous8.YanoProto.Person, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> 
            getPersonFieldBuilder() {
          if (personBuilder_ == null) {
            personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                hu.unideb.inf.batfai.yanonymous8.YanoProto.Person, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder>(
                    person_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            person_ = null;
          }
          return personBuilder_;
        }

        // required .Person.Relations.Relation relation = 2;
        private hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation relation_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation.Relational;
        /**
         * <code>required .Person.Relations.Relation relation = 2;</code>
         */
        public boolean hasRelation() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .Person.Relations.Relation relation = 2;</code>
         */
        public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation getRelation() {
          return relation_;
        }
        /**
         * <code>required .Person.Relations.Relation relation = 2;</code>
         */
        public Builder setRelation(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          relation_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .Person.Relations.Relation relation = 2;</code>
         */
        public Builder clearRelation() {
          bitField0_ = (bitField0_ & ~0x00000002);
          relation_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Relation.Relational;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Person.Relations)
      }

      static {
        defaultInstance = new Relations(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Person.Relations)
    }

    private int bitField0_;
    // required int32 meId = 1;
    public static final int MEID_FIELD_NUMBER = 1;
    private int meId_;
    /**
     * <code>required int32 meId = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    public boolean hasMeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 meId = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    public int getMeId() {
      return meId_;
    }

    // optional int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // required .Person.Chosen chosen = 3;
    public static final int CHOSEN_FIELD_NUMBER = 3;
    private hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen chosen_;
    /**
     * <code>required .Person.Chosen chosen = 3;</code>
     */
    public boolean hasChosen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Person.Chosen chosen = 3;</code>
     */
    public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen getChosen() {
      return chosen_;
    }

    // optional .Person.Relations relations = 4;
    public static final int RELATIONS_FIELD_NUMBER = 4;
    private hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations relations_;
    /**
     * <code>optional .Person.Relations relations = 4;</code>
     */
    public boolean hasRelations() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Person.Relations relations = 4;</code>
     */
    public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations getRelations() {
      return relations_;
    }
    /**
     * <code>optional .Person.Relations relations = 4;</code>
     */
    public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.RelationsOrBuilder getRelationsOrBuilder() {
      return relations_;
    }

    private void initFields() {
      meId_ = 0;
      id_ = 0;
      chosen_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen.Android;
      relations_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChosen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRelations()) {
        if (!getRelations().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, meId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, chosen_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, relations_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, meId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, chosen_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, relations_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.class, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder.class);
      }

      // Construct using hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRelationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        meId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        chosen_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen.Android;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (relationsBuilder_ == null) {
          relations_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.getDefaultInstance();
        } else {
          relationsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Person_descriptor;
      }

      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person getDefaultInstanceForType() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.getDefaultInstance();
      }

      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person build() {
        hu.unideb.inf.batfai.yanonymous8.YanoProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person buildPartial() {
        hu.unideb.inf.batfai.yanonymous8.YanoProto.Person result = new hu.unideb.inf.batfai.yanonymous8.YanoProto.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.meId_ = meId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chosen_ = chosen_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (relationsBuilder_ == null) {
          result.relations_ = relations_;
        } else {
          result.relations_ = relationsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hu.unideb.inf.batfai.yanonymous8.YanoProto.Person) {
          return mergeFrom((hu.unideb.inf.batfai.yanonymous8.YanoProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person other) {
        if (other == hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.getDefaultInstance()) return this;
        if (other.hasMeId()) {
          setMeId(other.getMeId());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasChosen()) {
          setChosen(other.getChosen());
        }
        if (other.hasRelations()) {
          mergeRelations(other.getRelations());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMeId()) {
          
          return false;
        }
        if (!hasChosen()) {
          
          return false;
        }
        if (hasRelations()) {
          if (!getRelations().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hu.unideb.inf.batfai.yanonymous8.YanoProto.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hu.unideb.inf.batfai.yanonymous8.YanoProto.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 meId = 1;
      private int meId_ ;
      /**
       * <code>required int32 meId = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public boolean hasMeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 meId = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public int getMeId() {
        return meId_;
      }
      /**
       * <code>required int32 meId = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public Builder setMeId(int value) {
        bitField0_ |= 0x00000001;
        meId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 meId = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public Builder clearMeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        meId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 id = 2;
      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // required .Person.Chosen chosen = 3;
      private hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen chosen_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen.Android;
      /**
       * <code>required .Person.Chosen chosen = 3;</code>
       */
      public boolean hasChosen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Person.Chosen chosen = 3;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen getChosen() {
        return chosen_;
      }
      /**
       * <code>required .Person.Chosen chosen = 3;</code>
       */
      public Builder setChosen(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        chosen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Person.Chosen chosen = 3;</code>
       */
      public Builder clearChosen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chosen_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Chosen.Android;
        onChanged();
        return this;
      }

      // optional .Person.Relations relations = 4;
      private hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations relations_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.RelationsOrBuilder> relationsBuilder_;
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      public boolean hasRelations() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations getRelations() {
        if (relationsBuilder_ == null) {
          return relations_;
        } else {
          return relationsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      public Builder setRelations(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          relations_ = value;
          onChanged();
        } else {
          relationsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      public Builder setRelations(
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          relations_ = builderForValue.build();
          onChanged();
        } else {
          relationsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      public Builder mergeRelations(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations value) {
        if (relationsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              relations_ != hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.getDefaultInstance()) {
            relations_ =
              hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.newBuilder(relations_).mergeFrom(value).buildPartial();
          } else {
            relations_ = value;
          }
          onChanged();
        } else {
          relationsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      public Builder clearRelations() {
        if (relationsBuilder_ == null) {
          relations_ = hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.getDefaultInstance();
          onChanged();
        } else {
          relationsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Builder getRelationsBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getRelationsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.RelationsOrBuilder getRelationsOrBuilder() {
        if (relationsBuilder_ != null) {
          return relationsBuilder_.getMessageOrBuilder();
        } else {
          return relations_;
        }
      }
      /**
       * <code>optional .Person.Relations relations = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.RelationsOrBuilder> 
          getRelationsFieldBuilder() {
        if (relationsBuilder_ == null) {
          relationsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Relations.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.RelationsOrBuilder>(
                  relations_,
                  getParentForChildren(),
                  isClean());
          relations_ = null;
        }
        return relationsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  public interface DatasOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Person Person = 1;
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> 
        getPersonList();
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    hu.unideb.inf.batfai.yanonymous8.YanoProto.Person getPerson(int index);
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    java.util.List<? extends hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Datas}
   */
  public static final class Datas extends
      com.google.protobuf.GeneratedMessage
      implements DatasOrBuilder {
    // Use Datas.newBuilder() to construct.
    private Datas(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Datas(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Datas defaultInstance;
    public static Datas getDefaultInstance() {
      return defaultInstance;
    }

    public Datas getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Datas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Datas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Datas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas.class, hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas.Builder.class);
    }

    public static com.google.protobuf.Parser<Datas> PARSER =
        new com.google.protobuf.AbstractParser<Datas>() {
      public Datas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Datas(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Datas> getParserForType() {
      return PARSER;
    }

    // repeated .Person Person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> person_;
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public java.util.List<? extends hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Datas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements hu.unideb.inf.batfai.yanonymous8.YanoProto.DatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Datas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Datas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas.class, hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas.Builder.class);
      }

      // Construct using hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.internal_static_Datas_descriptor;
      }

      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas getDefaultInstanceForType() {
        return hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas.getDefaultInstance();
      }

      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas build() {
        hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas buildPartial() {
        hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas result = new hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas) {
          return mergeFrom((hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas other) {
        if (other == hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hu.unideb.inf.batfai.yanonymous8.YanoProto.Datas) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Person Person = 1;
      private java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder setPerson(
          int index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder setPerson(
          int index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addPerson(hu.unideb.inf.batfai.yanonymous8.YanoProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addPerson(
          int index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addPerson(
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addPerson(
          int index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends hu.unideb.inf.batfai.yanonymous8.YanoProto.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public java.util.List<? extends hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public java.util.List<hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          hu.unideb.inf.batfai.yanonymous8.YanoProto.Person, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              hu.unideb.inf.batfai.yanonymous8.YanoProto.Person, hu.unideb.inf.batfai.yanonymous8.YanoProto.Person.Builder, hu.unideb.inf.batfai.yanonymous8.YanoProto.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Datas)
    }

    static {
      defaultInstance = new Datas(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Datas)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_Relations_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_Relations_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Datas_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Datas_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protobuf/yano.proto\"\343\002\n\006Person\022\014\n\004meId" +
      "\030\001 \002(\005\022\n\n\002id\030\002 \001(\005\022\036\n\006chosen\030\003 \002(\0162\016.Per" +
      "son.Chosen\022$\n\trelations\030\004 \001(\0132\021.Person.R" +
      "elations\032\277\001\n\tRelations\022\027\n\006Person\030\001 \003(\0132\007" +
      ".Person\022,\n\010relation\030\002 \002(\0162\032.Person.Relat" +
      "ions.Relation\"k\n\010Relation\022\016\n\nRelational\020" +
      "\001\022\n\n\006Friend\020\002\022\016\n\nGirlfriend\020\003\022\r\n\tBoyfrie" +
      "nd\020\004\022\n\n\006Father\020\005\022\n\n\006Mother\020\006\022\014\n\010Neighbor" +
      "\020\007\"7\n\006Chosen\022\013\n\007Android\020\001\022\007\n\003iOS\020\002\022\013\n\007Wi" +
      "ndows\020\003\022\n\n\006Others\020\004\" \n\005Datas\022\027\n\006Person\030\001",
      " \003(\0132\007.PersonB-\n hu.unideb.inf.batfai.ya" +
      "nonymous8B\tYanoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_descriptor,
              new java.lang.String[] { "MeId", "Id", "Chosen", "Relations", });
          internal_static_Person_Relations_descriptor =
            internal_static_Person_descriptor.getNestedTypes().get(0);
          internal_static_Person_Relations_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_Relations_descriptor,
              new java.lang.String[] { "Person", "Relation", });
          internal_static_Datas_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Datas_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Datas_descriptor,
              new java.lang.String[] { "Person", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
