// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/yano.proto

package yano_server;

public final class YanoProto {
  private YanoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface YanoDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 meId = 1;
    /**
     * <code>required int32 meId = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    boolean hasMeId();
    /**
     * <code>required int32 meId = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    int getMeId();

    // optional int32 id = 2;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    int getId();

    // required .YanoData.Chosen chosen = 3;
    /**
     * <code>required .YanoData.Chosen chosen = 3;</code>
     */
    boolean hasChosen();
    /**
     * <code>required .YanoData.Chosen chosen = 3;</code>
     */
    yano_server.YanoProto.YanoData.Chosen getChosen();

    // optional .YanoData.Relations relations = 4;
    /**
     * <code>optional .YanoData.Relations relations = 4;</code>
     */
    boolean hasRelations();
    /**
     * <code>optional .YanoData.Relations relations = 4;</code>
     */
    yano_server.YanoProto.YanoData.Relations getRelations();
    /**
     * <code>optional .YanoData.Relations relations = 4;</code>
     */
    yano_server.YanoProto.YanoData.RelationsOrBuilder getRelationsOrBuilder();
  }
  /**
   * Protobuf type {@code YanoData}
   */
  public static final class YanoData extends
      com.google.protobuf.GeneratedMessage
      implements YanoDataOrBuilder {
    // Use YanoData.newBuilder() to construct.
    private YanoData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private YanoData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final YanoData defaultInstance;
    public static YanoData getDefaultInstance() {
      return defaultInstance;
    }

    public YanoData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private YanoData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              meId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              yano_server.YanoProto.YanoData.Chosen value = yano_server.YanoProto.YanoData.Chosen.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                chosen_ = value;
              }
              break;
            }
            case 34: {
              yano_server.YanoProto.YanoData.Relations.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = relations_.toBuilder();
              }
              relations_ = input.readMessage(yano_server.YanoProto.YanoData.Relations.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(relations_);
                relations_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yano_server.YanoProto.internal_static_YanoData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yano_server.YanoProto.internal_static_YanoData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yano_server.YanoProto.YanoData.class, yano_server.YanoProto.YanoData.Builder.class);
    }

    public static com.google.protobuf.Parser<YanoData> PARSER =
        new com.google.protobuf.AbstractParser<YanoData>() {
      public YanoData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new YanoData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<YanoData> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code YanoData.Chosen}
     *
     * <pre>
     * Kit/mit választott
     * </pre>
     */
    public enum Chosen
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Valami1 = 1;</code>
       */
      Valami1(0, 1),
      /**
       * <code>Valami2 = 2;</code>
       */
      Valami2(1, 2),
      ;

      /**
       * <code>Valami1 = 1;</code>
       */
      public static final int Valami1_VALUE = 1;
      /**
       * <code>Valami2 = 2;</code>
       */
      public static final int Valami2_VALUE = 2;


      public final int getNumber() { return value; }

      public static Chosen valueOf(int value) {
        switch (value) {
          case 1: return Valami1;
          case 2: return Valami2;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Chosen>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Chosen>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Chosen>() {
              public Chosen findValueByNumber(int number) {
                return Chosen.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return yano_server.YanoProto.YanoData.getDescriptor().getEnumTypes().get(0);
      }

      private static final Chosen[] VALUES = values();

      public static Chosen valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Chosen(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:YanoData.Chosen)
    }

    public interface RelationsOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // repeated .YanoData yanodata = 1;
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      java.util.List<yano_server.YanoProto.YanoData> 
          getYanodataList();
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      yano_server.YanoProto.YanoData getYanodata(int index);
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      int getYanodataCount();
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      java.util.List<? extends yano_server.YanoProto.YanoDataOrBuilder> 
          getYanodataOrBuilderList();
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      yano_server.YanoProto.YanoDataOrBuilder getYanodataOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code YanoData.Relations}
     */
    public static final class Relations extends
        com.google.protobuf.GeneratedMessage
        implements RelationsOrBuilder {
      // Use Relations.newBuilder() to construct.
      private Relations(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Relations(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Relations defaultInstance;
      public static Relations getDefaultInstance() {
        return defaultInstance;
      }

      public Relations getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Relations(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  yanodata_ = new java.util.ArrayList<yano_server.YanoProto.YanoData>();
                  mutable_bitField0_ |= 0x00000001;
                }
                yanodata_.add(input.readMessage(yano_server.YanoProto.YanoData.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            yanodata_ = java.util.Collections.unmodifiableList(yanodata_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yano_server.YanoProto.internal_static_YanoData_Relations_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yano_server.YanoProto.internal_static_YanoData_Relations_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yano_server.YanoProto.YanoData.Relations.class, yano_server.YanoProto.YanoData.Relations.Builder.class);
      }

      public static com.google.protobuf.Parser<Relations> PARSER =
          new com.google.protobuf.AbstractParser<Relations>() {
        public Relations parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Relations(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Relations> getParserForType() {
        return PARSER;
      }

      // repeated .YanoData yanodata = 1;
      public static final int YANODATA_FIELD_NUMBER = 1;
      private java.util.List<yano_server.YanoProto.YanoData> yanodata_;
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      public java.util.List<yano_server.YanoProto.YanoData> getYanodataList() {
        return yanodata_;
      }
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      public java.util.List<? extends yano_server.YanoProto.YanoDataOrBuilder> 
          getYanodataOrBuilderList() {
        return yanodata_;
      }
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      public int getYanodataCount() {
        return yanodata_.size();
      }
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      public yano_server.YanoProto.YanoData getYanodata(int index) {
        return yanodata_.get(index);
      }
      /**
       * <code>repeated .YanoData yanodata = 1;</code>
       */
      public yano_server.YanoProto.YanoDataOrBuilder getYanodataOrBuilder(
          int index) {
        return yanodata_.get(index);
      }

      private void initFields() {
        yanodata_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        for (int i = 0; i < getYanodataCount(); i++) {
          if (!getYanodata(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        for (int i = 0; i < yanodata_.size(); i++) {
          output.writeMessage(1, yanodata_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < yanodata_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, yanodata_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static yano_server.YanoProto.YanoData.Relations parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static yano_server.YanoProto.YanoData.Relations parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static yano_server.YanoProto.YanoData.Relations parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static yano_server.YanoProto.YanoData.Relations parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static yano_server.YanoProto.YanoData.Relations parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static yano_server.YanoProto.YanoData.Relations parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static yano_server.YanoProto.YanoData.Relations parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static yano_server.YanoProto.YanoData.Relations parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static yano_server.YanoProto.YanoData.Relations parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static yano_server.YanoProto.YanoData.Relations parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(yano_server.YanoProto.YanoData.Relations prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code YanoData.Relations}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements yano_server.YanoProto.YanoData.RelationsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return yano_server.YanoProto.internal_static_YanoData_Relations_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return yano_server.YanoProto.internal_static_YanoData_Relations_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  yano_server.YanoProto.YanoData.Relations.class, yano_server.YanoProto.YanoData.Relations.Builder.class);
        }

        // Construct using yano_server.YanoProto.YanoData.Relations.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getYanodataFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (yanodataBuilder_ == null) {
            yanodata_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            yanodataBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return yano_server.YanoProto.internal_static_YanoData_Relations_descriptor;
        }

        public yano_server.YanoProto.YanoData.Relations getDefaultInstanceForType() {
          return yano_server.YanoProto.YanoData.Relations.getDefaultInstance();
        }

        public yano_server.YanoProto.YanoData.Relations build() {
          yano_server.YanoProto.YanoData.Relations result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public yano_server.YanoProto.YanoData.Relations buildPartial() {
          yano_server.YanoProto.YanoData.Relations result = new yano_server.YanoProto.YanoData.Relations(this);
          int from_bitField0_ = bitField0_;
          if (yanodataBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              yanodata_ = java.util.Collections.unmodifiableList(yanodata_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.yanodata_ = yanodata_;
          } else {
            result.yanodata_ = yanodataBuilder_.build();
          }
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof yano_server.YanoProto.YanoData.Relations) {
            return mergeFrom((yano_server.YanoProto.YanoData.Relations)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(yano_server.YanoProto.YanoData.Relations other) {
          if (other == yano_server.YanoProto.YanoData.Relations.getDefaultInstance()) return this;
          if (yanodataBuilder_ == null) {
            if (!other.yanodata_.isEmpty()) {
              if (yanodata_.isEmpty()) {
                yanodata_ = other.yanodata_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureYanodataIsMutable();
                yanodata_.addAll(other.yanodata_);
              }
              onChanged();
            }
          } else {
            if (!other.yanodata_.isEmpty()) {
              if (yanodataBuilder_.isEmpty()) {
                yanodataBuilder_.dispose();
                yanodataBuilder_ = null;
                yanodata_ = other.yanodata_;
                bitField0_ = (bitField0_ & ~0x00000001);
                yanodataBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getYanodataFieldBuilder() : null;
              } else {
                yanodataBuilder_.addAllMessages(other.yanodata_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          for (int i = 0; i < getYanodataCount(); i++) {
            if (!getYanodata(i).isInitialized()) {
              
              return false;
            }
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          yano_server.YanoProto.YanoData.Relations parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (yano_server.YanoProto.YanoData.Relations) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // repeated .YanoData yanodata = 1;
        private java.util.List<yano_server.YanoProto.YanoData> yanodata_ =
          java.util.Collections.emptyList();
        private void ensureYanodataIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            yanodata_ = new java.util.ArrayList<yano_server.YanoProto.YanoData>(yanodata_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            yano_server.YanoProto.YanoData, yano_server.YanoProto.YanoData.Builder, yano_server.YanoProto.YanoDataOrBuilder> yanodataBuilder_;

        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public java.util.List<yano_server.YanoProto.YanoData> getYanodataList() {
          if (yanodataBuilder_ == null) {
            return java.util.Collections.unmodifiableList(yanodata_);
          } else {
            return yanodataBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public int getYanodataCount() {
          if (yanodataBuilder_ == null) {
            return yanodata_.size();
          } else {
            return yanodataBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public yano_server.YanoProto.YanoData getYanodata(int index) {
          if (yanodataBuilder_ == null) {
            return yanodata_.get(index);
          } else {
            return yanodataBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder setYanodata(
            int index, yano_server.YanoProto.YanoData value) {
          if (yanodataBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureYanodataIsMutable();
            yanodata_.set(index, value);
            onChanged();
          } else {
            yanodataBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder setYanodata(
            int index, yano_server.YanoProto.YanoData.Builder builderForValue) {
          if (yanodataBuilder_ == null) {
            ensureYanodataIsMutable();
            yanodata_.set(index, builderForValue.build());
            onChanged();
          } else {
            yanodataBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder addYanodata(yano_server.YanoProto.YanoData value) {
          if (yanodataBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureYanodataIsMutable();
            yanodata_.add(value);
            onChanged();
          } else {
            yanodataBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder addYanodata(
            int index, yano_server.YanoProto.YanoData value) {
          if (yanodataBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureYanodataIsMutable();
            yanodata_.add(index, value);
            onChanged();
          } else {
            yanodataBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder addYanodata(
            yano_server.YanoProto.YanoData.Builder builderForValue) {
          if (yanodataBuilder_ == null) {
            ensureYanodataIsMutable();
            yanodata_.add(builderForValue.build());
            onChanged();
          } else {
            yanodataBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder addYanodata(
            int index, yano_server.YanoProto.YanoData.Builder builderForValue) {
          if (yanodataBuilder_ == null) {
            ensureYanodataIsMutable();
            yanodata_.add(index, builderForValue.build());
            onChanged();
          } else {
            yanodataBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder addAllYanodata(
            java.lang.Iterable<? extends yano_server.YanoProto.YanoData> values) {
          if (yanodataBuilder_ == null) {
            ensureYanodataIsMutable();
            super.addAll(values, yanodata_);
            onChanged();
          } else {
            yanodataBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder clearYanodata() {
          if (yanodataBuilder_ == null) {
            yanodata_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            yanodataBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public Builder removeYanodata(int index) {
          if (yanodataBuilder_ == null) {
            ensureYanodataIsMutable();
            yanodata_.remove(index);
            onChanged();
          } else {
            yanodataBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public yano_server.YanoProto.YanoData.Builder getYanodataBuilder(
            int index) {
          return getYanodataFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public yano_server.YanoProto.YanoDataOrBuilder getYanodataOrBuilder(
            int index) {
          if (yanodataBuilder_ == null) {
            return yanodata_.get(index);  } else {
            return yanodataBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public java.util.List<? extends yano_server.YanoProto.YanoDataOrBuilder> 
             getYanodataOrBuilderList() {
          if (yanodataBuilder_ != null) {
            return yanodataBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(yanodata_);
          }
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public yano_server.YanoProto.YanoData.Builder addYanodataBuilder() {
          return getYanodataFieldBuilder().addBuilder(
              yano_server.YanoProto.YanoData.getDefaultInstance());
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public yano_server.YanoProto.YanoData.Builder addYanodataBuilder(
            int index) {
          return getYanodataFieldBuilder().addBuilder(
              index, yano_server.YanoProto.YanoData.getDefaultInstance());
        }
        /**
         * <code>repeated .YanoData yanodata = 1;</code>
         */
        public java.util.List<yano_server.YanoProto.YanoData.Builder> 
             getYanodataBuilderList() {
          return getYanodataFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            yano_server.YanoProto.YanoData, yano_server.YanoProto.YanoData.Builder, yano_server.YanoProto.YanoDataOrBuilder> 
            getYanodataFieldBuilder() {
          if (yanodataBuilder_ == null) {
            yanodataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                yano_server.YanoProto.YanoData, yano_server.YanoProto.YanoData.Builder, yano_server.YanoProto.YanoDataOrBuilder>(
                    yanodata_,
                    ((bitField0_ & 0x00000001) == 0x00000001),
                    getParentForChildren(),
                    isClean());
            yanodata_ = null;
          }
          return yanodataBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:YanoData.Relations)
      }

      static {
        defaultInstance = new Relations(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:YanoData.Relations)
    }

    private int bitField0_;
    // required int32 meId = 1;
    public static final int MEID_FIELD_NUMBER = 1;
    private int meId_;
    /**
     * <code>required int32 meId = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    public boolean hasMeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 meId = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    public int getMeId() {
      return meId_;
    }

    // optional int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // required .YanoData.Chosen chosen = 3;
    public static final int CHOSEN_FIELD_NUMBER = 3;
    private yano_server.YanoProto.YanoData.Chosen chosen_;
    /**
     * <code>required .YanoData.Chosen chosen = 3;</code>
     */
    public boolean hasChosen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .YanoData.Chosen chosen = 3;</code>
     */
    public yano_server.YanoProto.YanoData.Chosen getChosen() {
      return chosen_;
    }

    // optional .YanoData.Relations relations = 4;
    public static final int RELATIONS_FIELD_NUMBER = 4;
    private yano_server.YanoProto.YanoData.Relations relations_;
    /**
     * <code>optional .YanoData.Relations relations = 4;</code>
     */
    public boolean hasRelations() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .YanoData.Relations relations = 4;</code>
     */
    public yano_server.YanoProto.YanoData.Relations getRelations() {
      return relations_;
    }
    /**
     * <code>optional .YanoData.Relations relations = 4;</code>
     */
    public yano_server.YanoProto.YanoData.RelationsOrBuilder getRelationsOrBuilder() {
      return relations_;
    }

    private void initFields() {
      meId_ = 0;
      id_ = 0;
      chosen_ = yano_server.YanoProto.YanoData.Chosen.Valami1;
      relations_ = yano_server.YanoProto.YanoData.Relations.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChosen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRelations()) {
        if (!getRelations().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, meId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, chosen_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, relations_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, meId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, chosen_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, relations_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yano_server.YanoProto.YanoData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yano_server.YanoProto.YanoData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yano_server.YanoProto.YanoData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yano_server.YanoProto.YanoData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yano_server.YanoProto.YanoData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yano_server.YanoProto.YanoData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yano_server.YanoProto.YanoData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yano_server.YanoProto.YanoData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yano_server.YanoProto.YanoData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yano_server.YanoProto.YanoData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yano_server.YanoProto.YanoData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code YanoData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements yano_server.YanoProto.YanoDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yano_server.YanoProto.internal_static_YanoData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yano_server.YanoProto.internal_static_YanoData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yano_server.YanoProto.YanoData.class, yano_server.YanoProto.YanoData.Builder.class);
      }

      // Construct using yano_server.YanoProto.YanoData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRelationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        meId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        chosen_ = yano_server.YanoProto.YanoData.Chosen.Valami1;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (relationsBuilder_ == null) {
          relations_ = yano_server.YanoProto.YanoData.Relations.getDefaultInstance();
        } else {
          relationsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yano_server.YanoProto.internal_static_YanoData_descriptor;
      }

      public yano_server.YanoProto.YanoData getDefaultInstanceForType() {
        return yano_server.YanoProto.YanoData.getDefaultInstance();
      }

      public yano_server.YanoProto.YanoData build() {
        yano_server.YanoProto.YanoData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yano_server.YanoProto.YanoData buildPartial() {
        yano_server.YanoProto.YanoData result = new yano_server.YanoProto.YanoData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.meId_ = meId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chosen_ = chosen_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (relationsBuilder_ == null) {
          result.relations_ = relations_;
        } else {
          result.relations_ = relationsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yano_server.YanoProto.YanoData) {
          return mergeFrom((yano_server.YanoProto.YanoData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yano_server.YanoProto.YanoData other) {
        if (other == yano_server.YanoProto.YanoData.getDefaultInstance()) return this;
        if (other.hasMeId()) {
          setMeId(other.getMeId());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasChosen()) {
          setChosen(other.getChosen());
        }
        if (other.hasRelations()) {
          mergeRelations(other.getRelations());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMeId()) {
          
          return false;
        }
        if (!hasChosen()) {
          
          return false;
        }
        if (hasRelations()) {
          if (!getRelations().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yano_server.YanoProto.YanoData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yano_server.YanoProto.YanoData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 meId = 1;
      private int meId_ ;
      /**
       * <code>required int32 meId = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public boolean hasMeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 meId = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public int getMeId() {
        return meId_;
      }
      /**
       * <code>required int32 meId = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public Builder setMeId(int value) {
        bitField0_ |= 0x00000001;
        meId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 meId = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public Builder clearMeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        meId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 id = 2;
      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // required .YanoData.Chosen chosen = 3;
      private yano_server.YanoProto.YanoData.Chosen chosen_ = yano_server.YanoProto.YanoData.Chosen.Valami1;
      /**
       * <code>required .YanoData.Chosen chosen = 3;</code>
       */
      public boolean hasChosen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .YanoData.Chosen chosen = 3;</code>
       */
      public yano_server.YanoProto.YanoData.Chosen getChosen() {
        return chosen_;
      }
      /**
       * <code>required .YanoData.Chosen chosen = 3;</code>
       */
      public Builder setChosen(yano_server.YanoProto.YanoData.Chosen value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        chosen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .YanoData.Chosen chosen = 3;</code>
       */
      public Builder clearChosen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chosen_ = yano_server.YanoProto.YanoData.Chosen.Valami1;
        onChanged();
        return this;
      }

      // optional .YanoData.Relations relations = 4;
      private yano_server.YanoProto.YanoData.Relations relations_ = yano_server.YanoProto.YanoData.Relations.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          yano_server.YanoProto.YanoData.Relations, yano_server.YanoProto.YanoData.Relations.Builder, yano_server.YanoProto.YanoData.RelationsOrBuilder> relationsBuilder_;
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      public boolean hasRelations() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      public yano_server.YanoProto.YanoData.Relations getRelations() {
        if (relationsBuilder_ == null) {
          return relations_;
        } else {
          return relationsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      public Builder setRelations(yano_server.YanoProto.YanoData.Relations value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          relations_ = value;
          onChanged();
        } else {
          relationsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      public Builder setRelations(
          yano_server.YanoProto.YanoData.Relations.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          relations_ = builderForValue.build();
          onChanged();
        } else {
          relationsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      public Builder mergeRelations(yano_server.YanoProto.YanoData.Relations value) {
        if (relationsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              relations_ != yano_server.YanoProto.YanoData.Relations.getDefaultInstance()) {
            relations_ =
              yano_server.YanoProto.YanoData.Relations.newBuilder(relations_).mergeFrom(value).buildPartial();
          } else {
            relations_ = value;
          }
          onChanged();
        } else {
          relationsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      public Builder clearRelations() {
        if (relationsBuilder_ == null) {
          relations_ = yano_server.YanoProto.YanoData.Relations.getDefaultInstance();
          onChanged();
        } else {
          relationsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      public yano_server.YanoProto.YanoData.Relations.Builder getRelationsBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getRelationsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      public yano_server.YanoProto.YanoData.RelationsOrBuilder getRelationsOrBuilder() {
        if (relationsBuilder_ != null) {
          return relationsBuilder_.getMessageOrBuilder();
        } else {
          return relations_;
        }
      }
      /**
       * <code>optional .YanoData.Relations relations = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          yano_server.YanoProto.YanoData.Relations, yano_server.YanoProto.YanoData.Relations.Builder, yano_server.YanoProto.YanoData.RelationsOrBuilder> 
          getRelationsFieldBuilder() {
        if (relationsBuilder_ == null) {
          relationsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              yano_server.YanoProto.YanoData.Relations, yano_server.YanoProto.YanoData.Relations.Builder, yano_server.YanoProto.YanoData.RelationsOrBuilder>(
                  relations_,
                  getParentForChildren(),
                  isClean());
          relations_ = null;
        }
        return relationsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:YanoData)
    }

    static {
      defaultInstance = new YanoData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:YanoData)
  }

  public interface DatasOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .YanoData yanoData = 1;
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    java.util.List<yano_server.YanoProto.YanoData> 
        getYanoDataList();
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    yano_server.YanoProto.YanoData getYanoData(int index);
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    int getYanoDataCount();
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    java.util.List<? extends yano_server.YanoProto.YanoDataOrBuilder> 
        getYanoDataOrBuilderList();
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    yano_server.YanoProto.YanoDataOrBuilder getYanoDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Datas}
   */
  public static final class Datas extends
      com.google.protobuf.GeneratedMessage
      implements DatasOrBuilder {
    // Use Datas.newBuilder() to construct.
    private Datas(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Datas(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Datas defaultInstance;
    public static Datas getDefaultInstance() {
      return defaultInstance;
    }

    public Datas getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Datas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                yanoData_ = new java.util.ArrayList<yano_server.YanoProto.YanoData>();
                mutable_bitField0_ |= 0x00000001;
              }
              yanoData_.add(input.readMessage(yano_server.YanoProto.YanoData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          yanoData_ = java.util.Collections.unmodifiableList(yanoData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yano_server.YanoProto.internal_static_Datas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yano_server.YanoProto.internal_static_Datas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yano_server.YanoProto.Datas.class, yano_server.YanoProto.Datas.Builder.class);
    }

    public static com.google.protobuf.Parser<Datas> PARSER =
        new com.google.protobuf.AbstractParser<Datas>() {
      public Datas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Datas(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Datas> getParserForType() {
      return PARSER;
    }

    // repeated .YanoData yanoData = 1;
    public static final int YANODATA_FIELD_NUMBER = 1;
    private java.util.List<yano_server.YanoProto.YanoData> yanoData_;
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    public java.util.List<yano_server.YanoProto.YanoData> getYanoDataList() {
      return yanoData_;
    }
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    public java.util.List<? extends yano_server.YanoProto.YanoDataOrBuilder> 
        getYanoDataOrBuilderList() {
      return yanoData_;
    }
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    public int getYanoDataCount() {
      return yanoData_.size();
    }
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    public yano_server.YanoProto.YanoData getYanoData(int index) {
      return yanoData_.get(index);
    }
    /**
     * <code>repeated .YanoData yanoData = 1;</code>
     */
    public yano_server.YanoProto.YanoDataOrBuilder getYanoDataOrBuilder(
        int index) {
      return yanoData_.get(index);
    }

    private void initFields() {
      yanoData_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getYanoDataCount(); i++) {
        if (!getYanoData(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < yanoData_.size(); i++) {
        output.writeMessage(1, yanoData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < yanoData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, yanoData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yano_server.YanoProto.Datas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yano_server.YanoProto.Datas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yano_server.YanoProto.Datas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yano_server.YanoProto.Datas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yano_server.YanoProto.Datas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yano_server.YanoProto.Datas prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Datas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements yano_server.YanoProto.DatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yano_server.YanoProto.internal_static_Datas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yano_server.YanoProto.internal_static_Datas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yano_server.YanoProto.Datas.class, yano_server.YanoProto.Datas.Builder.class);
      }

      // Construct using yano_server.YanoProto.Datas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getYanoDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (yanoDataBuilder_ == null) {
          yanoData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          yanoDataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yano_server.YanoProto.internal_static_Datas_descriptor;
      }

      public yano_server.YanoProto.Datas getDefaultInstanceForType() {
        return yano_server.YanoProto.Datas.getDefaultInstance();
      }

      public yano_server.YanoProto.Datas build() {
        yano_server.YanoProto.Datas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yano_server.YanoProto.Datas buildPartial() {
        yano_server.YanoProto.Datas result = new yano_server.YanoProto.Datas(this);
        int from_bitField0_ = bitField0_;
        if (yanoDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            yanoData_ = java.util.Collections.unmodifiableList(yanoData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.yanoData_ = yanoData_;
        } else {
          result.yanoData_ = yanoDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yano_server.YanoProto.Datas) {
          return mergeFrom((yano_server.YanoProto.Datas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yano_server.YanoProto.Datas other) {
        if (other == yano_server.YanoProto.Datas.getDefaultInstance()) return this;
        if (yanoDataBuilder_ == null) {
          if (!other.yanoData_.isEmpty()) {
            if (yanoData_.isEmpty()) {
              yanoData_ = other.yanoData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureYanoDataIsMutable();
              yanoData_.addAll(other.yanoData_);
            }
            onChanged();
          }
        } else {
          if (!other.yanoData_.isEmpty()) {
            if (yanoDataBuilder_.isEmpty()) {
              yanoDataBuilder_.dispose();
              yanoDataBuilder_ = null;
              yanoData_ = other.yanoData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              yanoDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getYanoDataFieldBuilder() : null;
            } else {
              yanoDataBuilder_.addAllMessages(other.yanoData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getYanoDataCount(); i++) {
          if (!getYanoData(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yano_server.YanoProto.Datas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yano_server.YanoProto.Datas) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .YanoData yanoData = 1;
      private java.util.List<yano_server.YanoProto.YanoData> yanoData_ =
        java.util.Collections.emptyList();
      private void ensureYanoDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          yanoData_ = new java.util.ArrayList<yano_server.YanoProto.YanoData>(yanoData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          yano_server.YanoProto.YanoData, yano_server.YanoProto.YanoData.Builder, yano_server.YanoProto.YanoDataOrBuilder> yanoDataBuilder_;

      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public java.util.List<yano_server.YanoProto.YanoData> getYanoDataList() {
        if (yanoDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(yanoData_);
        } else {
          return yanoDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public int getYanoDataCount() {
        if (yanoDataBuilder_ == null) {
          return yanoData_.size();
        } else {
          return yanoDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public yano_server.YanoProto.YanoData getYanoData(int index) {
        if (yanoDataBuilder_ == null) {
          return yanoData_.get(index);
        } else {
          return yanoDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder setYanoData(
          int index, yano_server.YanoProto.YanoData value) {
        if (yanoDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureYanoDataIsMutable();
          yanoData_.set(index, value);
          onChanged();
        } else {
          yanoDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder setYanoData(
          int index, yano_server.YanoProto.YanoData.Builder builderForValue) {
        if (yanoDataBuilder_ == null) {
          ensureYanoDataIsMutable();
          yanoData_.set(index, builderForValue.build());
          onChanged();
        } else {
          yanoDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder addYanoData(yano_server.YanoProto.YanoData value) {
        if (yanoDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureYanoDataIsMutable();
          yanoData_.add(value);
          onChanged();
        } else {
          yanoDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder addYanoData(
          int index, yano_server.YanoProto.YanoData value) {
        if (yanoDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureYanoDataIsMutable();
          yanoData_.add(index, value);
          onChanged();
        } else {
          yanoDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder addYanoData(
          yano_server.YanoProto.YanoData.Builder builderForValue) {
        if (yanoDataBuilder_ == null) {
          ensureYanoDataIsMutable();
          yanoData_.add(builderForValue.build());
          onChanged();
        } else {
          yanoDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder addYanoData(
          int index, yano_server.YanoProto.YanoData.Builder builderForValue) {
        if (yanoDataBuilder_ == null) {
          ensureYanoDataIsMutable();
          yanoData_.add(index, builderForValue.build());
          onChanged();
        } else {
          yanoDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder addAllYanoData(
          java.lang.Iterable<? extends yano_server.YanoProto.YanoData> values) {
        if (yanoDataBuilder_ == null) {
          ensureYanoDataIsMutable();
          super.addAll(values, yanoData_);
          onChanged();
        } else {
          yanoDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder clearYanoData() {
        if (yanoDataBuilder_ == null) {
          yanoData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          yanoDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public Builder removeYanoData(int index) {
        if (yanoDataBuilder_ == null) {
          ensureYanoDataIsMutable();
          yanoData_.remove(index);
          onChanged();
        } else {
          yanoDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public yano_server.YanoProto.YanoData.Builder getYanoDataBuilder(
          int index) {
        return getYanoDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public yano_server.YanoProto.YanoDataOrBuilder getYanoDataOrBuilder(
          int index) {
        if (yanoDataBuilder_ == null) {
          return yanoData_.get(index);  } else {
          return yanoDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public java.util.List<? extends yano_server.YanoProto.YanoDataOrBuilder> 
           getYanoDataOrBuilderList() {
        if (yanoDataBuilder_ != null) {
          return yanoDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(yanoData_);
        }
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public yano_server.YanoProto.YanoData.Builder addYanoDataBuilder() {
        return getYanoDataFieldBuilder().addBuilder(
            yano_server.YanoProto.YanoData.getDefaultInstance());
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public yano_server.YanoProto.YanoData.Builder addYanoDataBuilder(
          int index) {
        return getYanoDataFieldBuilder().addBuilder(
            index, yano_server.YanoProto.YanoData.getDefaultInstance());
      }
      /**
       * <code>repeated .YanoData yanoData = 1;</code>
       */
      public java.util.List<yano_server.YanoProto.YanoData.Builder> 
           getYanoDataBuilderList() {
        return getYanoDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          yano_server.YanoProto.YanoData, yano_server.YanoProto.YanoData.Builder, yano_server.YanoProto.YanoDataOrBuilder> 
          getYanoDataFieldBuilder() {
        if (yanoDataBuilder_ == null) {
          yanoDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              yano_server.YanoProto.YanoData, yano_server.YanoProto.YanoData.Builder, yano_server.YanoProto.YanoDataOrBuilder>(
                  yanoData_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          yanoData_ = null;
        }
        return yanoDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Datas)
    }

    static {
      defaultInstance = new Datas(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Datas)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YanoData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YanoData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_YanoData_Relations_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_YanoData_Relations_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Datas_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Datas_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/protobuf/yano.proto\"\274\001\n\010YanoD" +
      "ata\022\014\n\004meId\030\001 \002(\005\022\n\n\002id\030\002 \001(\005\022 \n\006chosen\030" +
      "\003 \002(\0162\020.YanoData.Chosen\022&\n\trelations\030\004 \001" +
      "(\0132\023.YanoData.Relations\032(\n\tRelations\022\033\n\010" +
      "yanodata\030\001 \003(\0132\t.YanoData\"\"\n\006Chosen\022\013\n\007V" +
      "alami1\020\001\022\013\n\007Valami2\020\002\"$\n\005Datas\022\033\n\010yanoDa" +
      "ta\030\001 \003(\0132\t.YanoDataB\030\n\013yano_serverB\tYano" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_YanoData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_YanoData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YanoData_descriptor,
              new java.lang.String[] { "MeId", "Id", "Chosen", "Relations", });
          internal_static_YanoData_Relations_descriptor =
            internal_static_YanoData_descriptor.getNestedTypes().get(0);
          internal_static_YanoData_Relations_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_YanoData_Relations_descriptor,
              new java.lang.String[] { "Yanodata", });
          internal_static_Datas_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Datas_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Datas_descriptor,
              new java.lang.String[] { "YanoData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
