// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/yano.proto

package yano_server;

public final class YanoProto {
  private YanoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string username = 1;
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    boolean hasUsername();
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    java.lang.String getUsername();
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    // optional string myFriend = 2;
    /**
     * <code>optional string myFriend = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    boolean hasMyFriend();
    /**
     * <code>optional string myFriend = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    java.lang.String getMyFriend();
    /**
     * <code>optional string myFriend = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    com.google.protobuf.ByteString
        getMyFriendBytes();

    // required .Person.Chosen chosen = 3;
    /**
     * <code>required .Person.Chosen chosen = 3;</code>
     */
    boolean hasChosen();
    /**
     * <code>required .Person.Chosen chosen = 3;</code>
     */
    yano_server.YanoProto.Person.Chosen getChosen();

    // optional .Person.Relation relation = 4;
    /**
     * <code>optional .Person.Relation relation = 4;</code>
     */
    boolean hasRelation();
    /**
     * <code>optional .Person.Relation relation = 4;</code>
     */
    yano_server.YanoProto.Person.Relation getRelation();
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Person(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              username_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              myFriend_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              yano_server.YanoProto.Person.Chosen value = yano_server.YanoProto.Person.Chosen.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                chosen_ = value;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              yano_server.YanoProto.Person.Relation value = yano_server.YanoProto.Person.Relation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                relation_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yano_server.YanoProto.internal_static_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yano_server.YanoProto.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yano_server.YanoProto.Person.class, yano_server.YanoProto.Person.Builder.class);
    }

    public static com.google.protobuf.Parser<Person> PARSER =
        new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Person.Chosen}
     *
     * <pre>
     * Kit/mit választott
     * </pre>
     */
    public enum Chosen
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Android = 1;</code>
       */
      Android(0, 1),
      /**
       * <code>iOS = 2;</code>
       */
      iOS(1, 2),
      /**
       * <code>Windows = 3;</code>
       */
      Windows(2, 3),
      /**
       * <code>Others = 4;</code>
       */
      Others(3, 4),
      ;

      /**
       * <code>Android = 1;</code>
       */
      public static final int Android_VALUE = 1;
      /**
       * <code>iOS = 2;</code>
       */
      public static final int iOS_VALUE = 2;
      /**
       * <code>Windows = 3;</code>
       */
      public static final int Windows_VALUE = 3;
      /**
       * <code>Others = 4;</code>
       */
      public static final int Others_VALUE = 4;


      public final int getNumber() { return value; }

      public static Chosen valueOf(int value) {
        switch (value) {
          case 1: return Android;
          case 2: return iOS;
          case 3: return Windows;
          case 4: return Others;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Chosen>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Chosen>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Chosen>() {
              public Chosen findValueByNumber(int number) {
                return Chosen.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return yano_server.YanoProto.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final Chosen[] VALUES = values();

      public static Chosen valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Chosen(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.Chosen)
    }

    /**
     * Protobuf enum {@code Person.Relation}
     */
    public enum Relation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Relationship = 1;</code>
       *
       * <pre>
       * rokoni
       * </pre>
       */
      Relationship(0, 1),
      /**
       * <code>Friend = 2;</code>
       *
       * <pre>
       * barát
       * </pre>
       */
      Friend(1, 2),
      /**
       * <code>Girlfriend = 3;</code>
       *
       * <pre>
       * csajom
       * </pre>
       */
      Girlfriend(2, 3),
      /**
       * <code>Boyfriend = 4;</code>
       *
       * <pre>
       * pasim
       * </pre>
       */
      Boyfriend(3, 4),
      /**
       * <code>Father = 5;</code>
       *
       * <pre>
       * apa
       * </pre>
       */
      Father(4, 5),
      /**
       * <code>Mother = 6;</code>
       *
       * <pre>
       * anya
       * </pre>
       */
      Mother(5, 6),
      /**
       * <code>Neighbor = 7;</code>
       *
       * <pre>
       * szomszéd
       * </pre>
       */
      Neighbor(6, 7),
      /**
       * <code>Testver = 8;</code>
       */
      Testver(7, 8),
      ;

      /**
       * <code>Relationship = 1;</code>
       *
       * <pre>
       * rokoni
       * </pre>
       */
      public static final int Relationship_VALUE = 1;
      /**
       * <code>Friend = 2;</code>
       *
       * <pre>
       * barát
       * </pre>
       */
      public static final int Friend_VALUE = 2;
      /**
       * <code>Girlfriend = 3;</code>
       *
       * <pre>
       * csajom
       * </pre>
       */
      public static final int Girlfriend_VALUE = 3;
      /**
       * <code>Boyfriend = 4;</code>
       *
       * <pre>
       * pasim
       * </pre>
       */
      public static final int Boyfriend_VALUE = 4;
      /**
       * <code>Father = 5;</code>
       *
       * <pre>
       * apa
       * </pre>
       */
      public static final int Father_VALUE = 5;
      /**
       * <code>Mother = 6;</code>
       *
       * <pre>
       * anya
       * </pre>
       */
      public static final int Mother_VALUE = 6;
      /**
       * <code>Neighbor = 7;</code>
       *
       * <pre>
       * szomszéd
       * </pre>
       */
      public static final int Neighbor_VALUE = 7;
      /**
       * <code>Testver = 8;</code>
       */
      public static final int Testver_VALUE = 8;


      public final int getNumber() { return value; }

      public static Relation valueOf(int value) {
        switch (value) {
          case 1: return Relationship;
          case 2: return Friend;
          case 3: return Girlfriend;
          case 4: return Boyfriend;
          case 5: return Father;
          case 6: return Mother;
          case 7: return Neighbor;
          case 8: return Testver;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Relation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Relation>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Relation>() {
              public Relation findValueByNumber(int number) {
                return Relation.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return yano_server.YanoProto.Person.getDescriptor().getEnumTypes().get(1);
      }

      private static final Relation[] VALUES = values();

      public static Relation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Relation(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Person.Relation)
    }

    private int bitField0_;
    // required string username = 1;
    public static final int USERNAME_FIELD_NUMBER = 1;
    private java.lang.Object username_;
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string username = 1;</code>
     *
     * <pre>
     * Saját azonosítóm
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string myFriend = 2;
    public static final int MYFRIEND_FIELD_NUMBER = 2;
    private java.lang.Object myFriend_;
    /**
     * <code>optional string myFriend = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    public boolean hasMyFriend() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string myFriend = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    public java.lang.String getMyFriend() {
      java.lang.Object ref = myFriend_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          myFriend_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string myFriend = 2;</code>
     *
     * <pre>
     * Akivel kapcsolatba annak az azonosítója
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMyFriendBytes() {
      java.lang.Object ref = myFriend_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        myFriend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .Person.Chosen chosen = 3;
    public static final int CHOSEN_FIELD_NUMBER = 3;
    private yano_server.YanoProto.Person.Chosen chosen_;
    /**
     * <code>required .Person.Chosen chosen = 3;</code>
     */
    public boolean hasChosen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Person.Chosen chosen = 3;</code>
     */
    public yano_server.YanoProto.Person.Chosen getChosen() {
      return chosen_;
    }

    // optional .Person.Relation relation = 4;
    public static final int RELATION_FIELD_NUMBER = 4;
    private yano_server.YanoProto.Person.Relation relation_;
    /**
     * <code>optional .Person.Relation relation = 4;</code>
     */
    public boolean hasRelation() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Person.Relation relation = 4;</code>
     */
    public yano_server.YanoProto.Person.Relation getRelation() {
      return relation_;
    }

    private void initFields() {
      username_ = "";
      myFriend_ = "";
      chosen_ = yano_server.YanoProto.Person.Chosen.Android;
      relation_ = yano_server.YanoProto.Person.Relation.Relationship;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUsername()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChosen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMyFriendBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, chosen_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, relation_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUsernameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMyFriendBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, chosen_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, relation_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yano_server.YanoProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yano_server.YanoProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yano_server.YanoProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yano_server.YanoProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yano_server.YanoProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yano_server.YanoProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yano_server.YanoProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yano_server.YanoProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yano_server.YanoProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yano_server.YanoProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yano_server.YanoProto.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements yano_server.YanoProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yano_server.YanoProto.internal_static_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yano_server.YanoProto.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yano_server.YanoProto.Person.class, yano_server.YanoProto.Person.Builder.class);
      }

      // Construct using yano_server.YanoProto.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        myFriend_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        chosen_ = yano_server.YanoProto.Person.Chosen.Android;
        bitField0_ = (bitField0_ & ~0x00000004);
        relation_ = yano_server.YanoProto.Person.Relation.Relationship;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yano_server.YanoProto.internal_static_Person_descriptor;
      }

      public yano_server.YanoProto.Person getDefaultInstanceForType() {
        return yano_server.YanoProto.Person.getDefaultInstance();
      }

      public yano_server.YanoProto.Person build() {
        yano_server.YanoProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yano_server.YanoProto.Person buildPartial() {
        yano_server.YanoProto.Person result = new yano_server.YanoProto.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.myFriend_ = myFriend_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chosen_ = chosen_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.relation_ = relation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yano_server.YanoProto.Person) {
          return mergeFrom((yano_server.YanoProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yano_server.YanoProto.Person other) {
        if (other == yano_server.YanoProto.Person.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasMyFriend()) {
          bitField0_ |= 0x00000002;
          myFriend_ = other.myFriend_;
          onChanged();
        }
        if (other.hasChosen()) {
          setChosen(other.getChosen());
        }
        if (other.hasRelation()) {
          setRelation(other.getRelation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUsername()) {
          
          return false;
        }
        if (!hasChosen()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yano_server.YanoProto.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yano_server.YanoProto.Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string username = 1;
      private java.lang.Object username_ = "";
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>required string username = 1;</code>
       *
       * <pre>
       * Saját azonosítóm
       * </pre>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      // optional string myFriend = 2;
      private java.lang.Object myFriend_ = "";
      /**
       * <code>optional string myFriend = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public boolean hasMyFriend() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string myFriend = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public java.lang.String getMyFriend() {
        java.lang.Object ref = myFriend_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          myFriend_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string myFriend = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMyFriendBytes() {
        java.lang.Object ref = myFriend_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          myFriend_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string myFriend = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public Builder setMyFriend(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        myFriend_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string myFriend = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public Builder clearMyFriend() {
        bitField0_ = (bitField0_ & ~0x00000002);
        myFriend_ = getDefaultInstance().getMyFriend();
        onChanged();
        return this;
      }
      /**
       * <code>optional string myFriend = 2;</code>
       *
       * <pre>
       * Akivel kapcsolatba annak az azonosítója
       * </pre>
       */
      public Builder setMyFriendBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        myFriend_ = value;
        onChanged();
        return this;
      }

      // required .Person.Chosen chosen = 3;
      private yano_server.YanoProto.Person.Chosen chosen_ = yano_server.YanoProto.Person.Chosen.Android;
      /**
       * <code>required .Person.Chosen chosen = 3;</code>
       */
      public boolean hasChosen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Person.Chosen chosen = 3;</code>
       */
      public yano_server.YanoProto.Person.Chosen getChosen() {
        return chosen_;
      }
      /**
       * <code>required .Person.Chosen chosen = 3;</code>
       */
      public Builder setChosen(yano_server.YanoProto.Person.Chosen value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        chosen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Person.Chosen chosen = 3;</code>
       */
      public Builder clearChosen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chosen_ = yano_server.YanoProto.Person.Chosen.Android;
        onChanged();
        return this;
      }

      // optional .Person.Relation relation = 4;
      private yano_server.YanoProto.Person.Relation relation_ = yano_server.YanoProto.Person.Relation.Relationship;
      /**
       * <code>optional .Person.Relation relation = 4;</code>
       */
      public boolean hasRelation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Person.Relation relation = 4;</code>
       */
      public yano_server.YanoProto.Person.Relation getRelation() {
        return relation_;
      }
      /**
       * <code>optional .Person.Relation relation = 4;</code>
       */
      public Builder setRelation(yano_server.YanoProto.Person.Relation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        relation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Person.Relation relation = 4;</code>
       */
      public Builder clearRelation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        relation_ = yano_server.YanoProto.Person.Relation.Relationship;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Person)
    }

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Person)
  }

  public interface DatasOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Person Person = 1;
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    java.util.List<yano_server.YanoProto.Person> 
        getPersonList();
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    yano_server.YanoProto.Person getPerson(int index);
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    java.util.List<? extends yano_server.YanoProto.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    yano_server.YanoProto.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Datas}
   */
  public static final class Datas extends
      com.google.protobuf.GeneratedMessage
      implements DatasOrBuilder {
    // Use Datas.newBuilder() to construct.
    private Datas(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Datas(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Datas defaultInstance;
    public static Datas getDefaultInstance() {
      return defaultInstance;
    }

    public Datas getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Datas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<yano_server.YanoProto.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(yano_server.YanoProto.Person.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yano_server.YanoProto.internal_static_Datas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yano_server.YanoProto.internal_static_Datas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yano_server.YanoProto.Datas.class, yano_server.YanoProto.Datas.Builder.class);
    }

    public static com.google.protobuf.Parser<Datas> PARSER =
        new com.google.protobuf.AbstractParser<Datas>() {
      public Datas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Datas(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Datas> getParserForType() {
      return PARSER;
    }

    // repeated .Person Person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<yano_server.YanoProto.Person> person_;
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public java.util.List<yano_server.YanoProto.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public java.util.List<? extends yano_server.YanoProto.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public yano_server.YanoProto.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .Person Person = 1;</code>
     */
    public yano_server.YanoProto.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yano_server.YanoProto.Datas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yano_server.YanoProto.Datas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yano_server.YanoProto.Datas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yano_server.YanoProto.Datas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yano_server.YanoProto.Datas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yano_server.YanoProto.Datas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yano_server.YanoProto.Datas prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Datas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements yano_server.YanoProto.DatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yano_server.YanoProto.internal_static_Datas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yano_server.YanoProto.internal_static_Datas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yano_server.YanoProto.Datas.class, yano_server.YanoProto.Datas.Builder.class);
      }

      // Construct using yano_server.YanoProto.Datas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yano_server.YanoProto.internal_static_Datas_descriptor;
      }

      public yano_server.YanoProto.Datas getDefaultInstanceForType() {
        return yano_server.YanoProto.Datas.getDefaultInstance();
      }

      public yano_server.YanoProto.Datas build() {
        yano_server.YanoProto.Datas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yano_server.YanoProto.Datas buildPartial() {
        yano_server.YanoProto.Datas result = new yano_server.YanoProto.Datas(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yano_server.YanoProto.Datas) {
          return mergeFrom((yano_server.YanoProto.Datas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yano_server.YanoProto.Datas other) {
        if (other == yano_server.YanoProto.Datas.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yano_server.YanoProto.Datas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yano_server.YanoProto.Datas) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Person Person = 1;
      private java.util.List<yano_server.YanoProto.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<yano_server.YanoProto.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          yano_server.YanoProto.Person, yano_server.YanoProto.Person.Builder, yano_server.YanoProto.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public java.util.List<yano_server.YanoProto.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public yano_server.YanoProto.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder setPerson(
          int index, yano_server.YanoProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder setPerson(
          int index, yano_server.YanoProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addPerson(yano_server.YanoProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addPerson(
          int index, yano_server.YanoProto.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addPerson(
          yano_server.YanoProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addPerson(
          int index, yano_server.YanoProto.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends yano_server.YanoProto.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public yano_server.YanoProto.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public yano_server.YanoProto.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public java.util.List<? extends yano_server.YanoProto.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public yano_server.YanoProto.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            yano_server.YanoProto.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public yano_server.YanoProto.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, yano_server.YanoProto.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .Person Person = 1;</code>
       */
      public java.util.List<yano_server.YanoProto.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          yano_server.YanoProto.Person, yano_server.YanoProto.Person.Builder, yano_server.YanoProto.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              yano_server.YanoProto.Person, yano_server.YanoProto.Person.Builder, yano_server.YanoProto.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Datas)
    }

    static {
      defaultInstance = new Datas(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Datas)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Datas_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Datas_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/protobuf/yano.proto\"\245\002\n\006Perso" +
      "n\022\020\n\010username\030\001 \002(\t\022\020\n\010myFriend\030\002 \001(\t\022\036\n" +
      "\006chosen\030\003 \002(\0162\016.Person.Chosen\022\"\n\010relatio" +
      "n\030\004 \001(\0162\020.Person.Relation\"7\n\006Chosen\022\013\n\007A" +
      "ndroid\020\001\022\007\n\003iOS\020\002\022\013\n\007Windows\020\003\022\n\n\006Others" +
      "\020\004\"z\n\010Relation\022\020\n\014Relationship\020\001\022\n\n\006Frie" +
      "nd\020\002\022\016\n\nGirlfriend\020\003\022\r\n\tBoyfriend\020\004\022\n\n\006F" +
      "ather\020\005\022\n\n\006Mother\020\006\022\014\n\010Neighbor\020\007\022\013\n\007Tes" +
      "tver\020\010\" \n\005Datas\022\027\n\006Person\030\001 \003(\0132\007.Person" +
      "B\030\n\013yano_serverB\tYanoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Person_descriptor,
              new java.lang.String[] { "Username", "MyFriend", "Chosen", "Relation", });
          internal_static_Datas_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Datas_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Datas_descriptor,
              new java.lang.String[] { "Person", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
